export const Users = [
  {
    id: 1,
    fullname: 'Кубик Владимир Владимирович',
    role: 'Руководитель',
    lastAuth: '01.01.2023',
    leader: '',
  },
  {
    id: 2,
    fullname: 'Иван Иванов',
    role: 'Сотрудник',
    lastAuth: '01.01.2024',
    leader: 'Владимир Владимирович',
  },
  {
    id: 3,
    fullname: 'Владимир Владимирович',
    role: 'Руководитель',
    lastAuth: '01.04.2023',
    leader: '',
  },
  {
    id: 4,
    fullname: 'Рубенштейн  Владимирович',
    role: 'Руководитель',
    lastAuth: '04.11.2023',
    leader: '',
  },
  {
    id: 5,
    fullname: 'Дмитрий Иванов Гендорович',
    role: 'Руководитель',
    lastAuth: '04.11.2023',
    leader: '',
  },
  {
    id: 6,
    fullname: 'Артем Бурдельный',
    role: 'Руководитель',
    lastAuth: '04.11.2023',
    leader: '',
  },
  {
    id: 7,
    fullname: 'Бахыт Мади',
    role: 'Сотрудник',
    lastAuth: '04.11.2023',
    leader: 'Артем Бурдельный',
  },
]
